name: UC Sync Automation

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: UC Student Sync
        uses: ./ # Use the action defined in this repository
        with:
          username: ${{ secrets.UC_USERNAME }}
          password: ${{ secrets.UC_PASSWORD }}
          commit_message: 'chore: auto-sync UC student files'
